"""Add observation validation module


Revision ID: 7be0cef93665
Revises: b7734f126b8c
Create Date: 2024-02-11 22:14:29.686374

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7be0cef93665"
down_revision = "b7734f126b8c"
branch_labels = None
depends_on = None


def upgrade():
    validation_status = postgresql.ENUM(
        "NOT_VALIDATED",
        "INVALID",
        "NON_VALIDATABLE",
        "VALIDATED",
        name="validationstatus",
    )
    validation_status.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("t_users", schema="gnc_core") as batch_op:
        batch_op.add_column(
            sa.Column(
                "validator",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=True,
            )
        )

    with op.batch_alter_table("t_obstax", schema="gnc_obstax") as batch_op:
        batch_op.add_column(
            sa.Column(
                "validation_status",
                validation_status,
                server_default="NOT_VALIDATED",
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("id_validator", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None,
            "t_users",
            ["id_validator"],
            ["id_user"],
            referent_schema="gnc_core",
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("t_obstax", schema="gnc_obstax") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("id_validator")
        batch_op.drop_column("validation_status")

    with op.batch_alter_table("t_users", schema="gnc_core") as batch_op:
        batch_op.drop_column("validator")

    # ### end Alembic commands ###
