"""review indexes

Revision ID: b7734f126b8c
Revises: e8c1cd57ad16
Create Date: 2024-02-08 16:11:21.388277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7734f126b8c"
down_revision = "e8c1cd57ad16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("t_custom_form", schema="gnc_core") as batch_op:
        batch_op.create_unique_constraint(None, ["id_form"])

    with op.batch_alter_table("t_projects", schema="gnc_core") as batch_op:
        batch_op.drop_constraint("t_projects_unique_id_project_key", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_gnc_core_t_projects_unique_id_project"),
            ["unique_id_project"],
            unique=True,
        )

    with op.batch_alter_table("cor_obstax_media", schema="gnc_obstax") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gnc_obstax_cor_obstax_media_id_data_source"),
            ["id_data_source"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_gnc_obstax_cor_obstax_media_id_media"), ["id_media"], unique=False
        )
        batch_op.create_unique_constraint(None, ["id_match"])

    with op.batch_alter_table("t_obstax", schema="gnc_obstax") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gnc_obstax_t_obstax_id_program"), ["id_program"], unique=False
        )
        batch_op.create_unique_constraint(None, ["id_observation"])

    with op.batch_alter_table("cor_program_typesites", schema="gnc_sites") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_cor_program_typesites_id_program"),
            ["id_program"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_cor_program_typesites_id_typesite"),
            ["id_typesite"],
            unique=False,
        )
        batch_op.create_unique_constraint(None, ["id_cor_program_typesite"])

    with op.batch_alter_table("cor_sites_obstax", schema="gnc_sites") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_cor_sites_obstax_id_obstax"), ["id_obstax"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_cor_sites_obstax_id_site"), ["id_site"], unique=False
        )
        batch_op.create_unique_constraint(None, ["id_cor_site_obstax"])

    with op.batch_alter_table("cor_visites_media", schema="gnc_sites") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_cor_visites_media_id_data_source"),
            ["id_data_source"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_cor_visites_media_id_media"), ["id_media"], unique=False
        )
        batch_op.create_unique_constraint(None, ["id_match"])

    with op.batch_alter_table("t_sites", schema="gnc_sites") as batch_op:
        batch_op.drop_constraint("t_sites_uuid_sinp_key", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_t_sites_id_program"), ["id_program"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_t_sites_id_type"), ["id_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_t_sites_uuid_sinp"), ["uuid_sinp"], unique=True
        )
        batch_op.create_unique_constraint(None, ["id_site"])

    with op.batch_alter_table("t_typesite", schema="gnc_sites") as batch_op:
        batch_op.create_unique_constraint(None, ["id_typesite"])

    with op.batch_alter_table("t_visit", schema="gnc_sites") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gnc_sites_t_visit_id_site"), ["id_site"], unique=False
        )
        batch_op.create_unique_constraint(None, ["id_visit"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("t_visit", schema="gnc_sites") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_gnc_sites_t_visit_id_site"))

    with op.batch_alter_table("t_typesite", schema="gnc_sites") as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("t_sites", schema="gnc_sites") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_gnc_sites_t_sites_uuid_sinp"))
        batch_op.drop_index(batch_op.f("ix_gnc_sites_t_sites_id_type"))
        batch_op.drop_index(batch_op.f("ix_gnc_sites_t_sites_id_program"))
        batch_op.create_unique_constraint("t_sites_uuid_sinp_key", ["uuid_sinp"])

    with op.batch_alter_table("cor_visites_media", schema="gnc_sites") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_gnc_sites_cor_visites_media_id_media"))
        batch_op.drop_index(batch_op.f("ix_gnc_sites_cor_visites_media_id_data_source"))

    with op.batch_alter_table("cor_sites_obstax", schema="gnc_sites") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_gnc_sites_cor_sites_obstax_id_site"))
        batch_op.drop_index(batch_op.f("ix_gnc_sites_cor_sites_obstax_id_obstax"))

    with op.batch_alter_table("cor_program_typesites", schema="gnc_sites") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_gnc_sites_cor_program_typesites_id_typesite"))
        batch_op.drop_index(batch_op.f("ix_gnc_sites_cor_program_typesites_id_program"))

    with op.batch_alter_table("t_obstax", schema="gnc_obstax") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_gnc_obstax_t_obstax_id_program"))

    with op.batch_alter_table("cor_obstax_media", schema="gnc_obstax") as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_gnc_obstax_cor_obstax_media_id_media"))
        batch_op.drop_index(batch_op.f("ix_gnc_obstax_cor_obstax_media_id_data_source"))

    with op.batch_alter_table("t_projects", schema="gnc_core") as batch_op:
        batch_op.drop_index(batch_op.f("ix_gnc_core_t_projects_unique_id_project"))
        batch_op.create_unique_constraint(
            "t_projects_unique_id_project_key", ["unique_id_project"]
        )

    with op.batch_alter_table("t_custom_form", schema="gnc_core") as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
